# Generated by Django 4.2.7 on 2026-01-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Auto-generated employee ID (e.g., PB-ST00123)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, help_text='Job role or designation', max_length=100),
        ),
    ]
