# Generated by Django 4.2.7 on 2026-01-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember_employee_id_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project assigned to this team member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='core.project'),
        ),
    ]
