# Generated by Django 4.2.7 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_logo',
            field=models.BinaryField(blank=True, help_text='Client logo stored as binary data', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_logo_name',
            field=models.CharField(blank=True, help_text='Original client logo filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_logo_type',
            field=models.CharField(blank=True, help_text='Client logo MIME type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_logo',
            field=models.BinaryField(blank=True, help_text='Contractor logo stored as binary data', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_logo_name',
            field=models.CharField(blank=True, help_text='Original contractor logo filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_logo_type',
            field=models.CharField(blank=True, help_text='Contractor logo MIME type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='address',
            field=models.TextField(blank=True, help_text='Residential address', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='site_inspector_attachment',
            field=models.BinaryField(blank=True, help_text='Site inspector attachment binary', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='site_inspector_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='site_inspector_attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='surveyor_attachment',
            field=models.BinaryField(blank=True, help_text='Surveyor attachment binary', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='surveyor_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='surveyor_attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='lab_technician_attachment',
            field=models.BinaryField(blank=True, help_text='Lab technician attachment binary', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='lab_technician_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='lab_technician_attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='material_engineer_attachment',
            field=models.BinaryField(blank=True, help_text='Material engineer attachment binary', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='material_engineer_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='material_engineer_attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='are_attachment',
            field=models.BinaryField(blank=True, help_text='A.R.E attachment binary', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='are_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='are_attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='resident_engineer_attachment',
            field=models.BinaryField(blank=True, help_text='Resident engineer attachment binary', null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='resident_engineer_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='resident_engineer_attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
